### ISSUE TITLE
Read config.json file fails several times

### ISSUE THREAD

**Issue by paquitodev** [tom-gangemi/Force.com-Replicator#8]
Hi there, I'm using your script to sync my local DB and I'm seeing this issue sometimes:

    [22-Aug-2015 20:14:01 America/New_York] PHP   1. {main}() /var/sync/sync_sandbox/replicator/Replicator.php:0
    [22-Aug-2015 20:14:01 America/New_York] PHP   2. Replicator->__construct() /var/sync/sync_sandbox/replicator/Replicator.php:351
    [22-Aug-2015 20:14:01 America/New_York] PHP   3. Replicator->loadConfig() /var/sync/sync_sandbox/replicator/Replicator.php:27
    [22-Aug-2015 20:14:01 America/New_York] PHP   4. file_get_contents() /var/sync/sync_sandbox/replicator/Replicator.php:244
    [22-Aug-2015 20:14:01 America/New_York] PHP Fatal error:  Uncaught exception 'Exception' with message 'error reading config.json' in /var/sync/sync_sandbox/replicator/Replicator.php:246
    Stack trace:
    #0 /var/sync/sync_sandbox/replicator/Replicator.php(27): Replicator->loadConfig()
    #1 /var/sync/sync_sandbox/replicator/Replicator.php(351): Replicator->__construct()
    #2 {main}
      thrown in /var/sync/sync_sandbox/replicator/Replicator.php on line 246

File exists, is readable by the script, giving a try to the script manually one time and it fails, second time it fails, third time and it works, four time and it fails, so, where is the issue here? why it fails sometimes and sometimes not? Can you take a look to this?

I'm running the script every night as a cronjob and it's failing due to this issue.

Thanks in advance

**Comment by tom-gangemi** [comment]
I'm not sure what is happening but I've added some improved error handling so that it is easier to narrow the issue down to a problem reading the config or an issue parsing it.

**Comment by reypm** [comment]
@tom-gangemi it's working now, thx
